export interface Template {
  name: string;
  label: string;
  description: string;
  icon: string;
  githubRepo?: string;
  tags: string[];
  files?: Record<string, string>;
}

export const STARTER_TEMPLATES: Template[] = [
  {
    name: 'nextjs',
    label: 'Next.js',
    description: 'Full-stack React framework with TypeScript',
    icon: '⚡',
    githubRepo: 'vercel/next.js/tree/canary/examples/hello-world',
    tags: ['react', 'typescript', 'ssr'],
    files: {
      'package.json': JSON.stringify({
        name: 'nextjs-app',
        version: '0.1.0',
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start'
        },
        dependencies: {
          next: '^14.0.0',
          react: '^18.0.0',
          'react-dom': '^18.0.0',
          typescript: '^5.0.0',
          '@types/node': '^20.0.0',
          '@types/react': '^18.0.0'
        }
      }, null, 2),
      'app/page.tsx': `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm">
        <h1 className="text-4xl font-bold">Next.js App</h1>
        <p className="text-xl mt-4">Welcome to your new Next.js application!</p>
      </div>
    </main>
  )
}`,
      'app/layout.tsx': `import './globals.css'

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by create-next-app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`,
      'app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;`
    }
  },
  {
    name: 'react',
    label: 'React',
    description: 'React app with Vite and TypeScript',
    icon: '⚛️',
    tags: ['react', 'vite', 'typescript'],
    files: {
      'package.json': JSON.stringify({
        name: 'react-app',
        version: '0.1.0',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview'
        },
        dependencies: {
          react: '^18.0.0',
          'react-dom': '^18.0.0'
        },
        devDependencies: {
          '@types/react': '^18.0.0',
          '@types/react-dom': '^18.0.0',
          '@vitejs/plugin-react': '^4.0.0',
          typescript: '^5.0.0',
          vite: '^5.0.0'
        }
      }, null, 2),
      'src/App.tsx': `import { useState } from 'react'
import './App.css'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
      <h1>React App</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
      </div>
    </div>
  )
}

export default App`,
      'src/main.tsx': `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`,
      'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>React App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`
    }
  },
  {
    name: 'vue',
    label: 'Vue.js',
    description: 'Vue 3 with Vite and TypeScript',
    icon: '🟢',
    tags: ['vue', 'vite', 'typescript'],
    files: {
      'package.json': JSON.stringify({
        name: 'vue-app',
        version: '0.1.0',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview'
        },
        dependencies: {
          vue: '^3.0.0'
        },
        devDependencies: {
          '@vitejs/plugin-vue': '^4.0.0',
          typescript: '^5.0.0',
          vite: '^5.0.0'
        }
      }, null, 2),
      'src/App.vue': `<template>
  <div id="app">
    <h1>Vue App</h1>
    <button @click="increment">Count: {{ count }}</button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)

const increment = () => {
  count.value++
}
</script>

<style scoped>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  text-align: center;
  margin-top: 60px;
}
</style>`,
      'src/main.ts': `import { createApp } from 'vue'
import App from './App.vue'

createApp(App).mount('#app')`,
      'index.html': `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vue App</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>`
    }
  },
  {
    name: 'svelte',
    label: 'Svelte',
    description: 'Svelte with SvelteKit and TypeScript',
    icon: '🧡',
    tags: ['svelte', 'sveltekit', 'typescript'],
    files: {
      'package.json': JSON.stringify({
        name: 'svelte-app',
        version: '0.1.0',
        scripts: {
          dev: 'vite dev',
          build: 'vite build',
          preview: 'vite preview'
        },
        dependencies: {
          '@sveltejs/kit': '^2.0.0'
        },
        devDependencies: {
          '@sveltejs/adapter-auto': '^3.0.0',
          '@sveltejs/vite-plugin-svelte': '^3.0.0',
          svelte: '^4.0.0',
          typescript: '^5.0.0',
          vite: '^5.0.0'
        }
      }, null, 2),
      'src/routes/+page.svelte': `<script lang="ts">
  let count = 0;

  function increment() {
    count++;
  }
</script>

<h1>Svelte App</h1>
<button on:click={increment}>Count: {count}</button>

<style>
  h1 {
    color: #ff3e00;
    text-transform: uppercase;
    font-size: 4em;
    font-weight: 100;
  }
</style>`,
      'src/app.html': `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="%sveltekit.assets%/favicon.png" />
    <meta name="viewport" content="width=device-width" />
    %sveltekit.head%
  </head>
  <body data-sveltekit-preload-data="hover">
    <div style="display: contents">%sveltekit.body%</div>
  </body>
</html>`
    }
  },
  {
    name: 'vanilla',
    label: 'Vanilla JS',
    description: 'Plain HTML, CSS, and JavaScript',
    icon: '🟡',
    tags: ['html', 'css', 'javascript'],
    files: {
      'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vanilla JS App</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <h1>Vanilla JavaScript App</h1>
        <button id="counter-btn">Count: 0</button>
    </div>
    <script src="script.js"></script>
</body>
</html>`,
      'style.css': `body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f0f0f0;
}

.container {
    max-width: 800px;
    margin: 0 auto;
    padding: 2rem;
    text-align: center;
}

h1 {
    color: #333;
    margin-bottom: 2rem;
}

button {
    background-color: #007bff;
    color: white;
    border: none;
    padding: 1rem 2rem;
    font-size: 1rem;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s;
}

button:hover {
    background-color: #0056b3;
}`,
      'script.js': `let count = 0;
const button = document.getElementById('counter-btn');

button.addEventListener('click', () => {
    count++;
    button.textContent = \`Count: \${count}\`;
});`
    }
  }
];

export default STARTER_TEMPLATES;